package com.example.iotapp;

import android.app.PendingIntent;
import android.content.Intent;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
//import mqtt library
import org.eclipse.paho.android.service.MqttAndroidClient;
import org.eclipse.paho.client.mqttv3.IMqttActionListener;
import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
import org.eclipse.paho.client.mqttv3.IMqttToken;
import org.eclipse.paho.client.mqttv3.MqttCallback;
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;
public class RemoteActivity extends AppCompatActivity {
    MqttAndroidClient client;
    MqttConnectOptions options;
    String BROKER_URL = "tcp://42.113.192.145:1883";

    //Client ID generated by paho library
    String CLIENT_ID = MqttClient.generateClientId();
    private MqttHandler mqttHandler;

    private ImageView btnPower;
    private ImageView btnRed;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout_remote);
        init();
    }

    private void init() {
        //check connection to internet
        btnPower = findViewById(R.id.btnPower);
        btnRed = findViewById(R.id.btnRed);
        mqttHandler = new MqttHandler();
        mqttHandler.connect(BROKER_URL,CLIENT_ID);
        //log the connection status

        btnPower.setOnClickListener(v -> {
            mqttHandler.publish("esp32/command","{\"data\":{\"macID\":\"40:22:D8:EA:06:F8\",\"command\":\"0\"}}");

        });
        btnRed.setOnClickListener(v -> {
            mqttHandler.publish("esp32/command","{\"data\":{\"macID\":\"40:22:D8:EA:06:F8\",\"command\":\"1\"}}");

        });
    }
}
